/**
 * Autogenerated by Thrift Compiler (0.9.1)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */

namespace LineSharp.Datatypes
{
  public enum ContactRelation
  {
    ONEWAY = 0,
    BOTH = 1,
    NOT_REGISTERED = 2,
  }
}
