/**
 * Autogenerated by Thrift Compiler (0.9.1)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */

namespace LineSharp.Datatypes
{
  public enum MIDType
  {
    USER = 0,
    ROOM = 1,
    GROUP = 2,
  }
}
