/**
 * Autogenerated by Thrift Compiler (0.9.1)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */

namespace LineSharp.Datatypes
{
  public enum NotificationStatus
  {
    NOTIFICATION_ITEM_EXIST = 1,
    TIMELINE_ITEM_EXIST = 2,
    NOTE_GROUP_NEW_ITEM_EXIST = 4,
    TIMELINE_BUDDYGROUP_CHANGED = 8,
    NOTE_ONE_TO_ONE_NEW_ITEM_EXIST = 16,
    ALBUM_ITEM_EXIST = 32,
    TIMELINE_ITEM_DELETED = 64,
  }
}
