/**
 * Autogenerated by Thrift Compiler (0.9.1)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
using System;
using System.Collections;
using System.Collections.Generic;
using System.Text;
using System.IO;
using Thrift;
using Thrift.Collections;
using System.Runtime.Serialization;
using Thrift.Protocol;
using Thrift.Transport;

namespace LineSharp.Datatypes
{

  #if !SILVERLIGHT
  [Serializable]
  #endif
  public partial class ProximityMatchCandidateResult : TBase
  {
    private List<Contact> _users;
    private List<Contact> _buddies;

    public List<Contact> Users
    {
      get
      {
        return _users;
      }
      set
      {
        __isset.users = true;
        this._users = value;
      }
    }

    public List<Contact> Buddies
    {
      get
      {
        return _buddies;
      }
      set
      {
        __isset.buddies = true;
        this._buddies = value;
      }
    }


    public Isset __isset;
    #if !SILVERLIGHT
    [Serializable]
    #endif
    public struct Isset {
      public bool users;
      public bool buddies;
    }

    public ProximityMatchCandidateResult() {
    }

    public void Read (TProtocol iprot)
    {
      TField field;
      iprot.ReadStructBegin();
      while (true)
      {
        field = iprot.ReadFieldBegin();
        if (field.Type == TType.Stop) { 
          break;
        }
        switch (field.ID)
        {
          case 1:
            if (field.Type == TType.List) {
              {
                Users = new List<Contact>();
                TList _list42 = iprot.ReadListBegin();
                for( int _i43 = 0; _i43 < _list42.Count; ++_i43)
                {
                  Contact _elem44 = new Contact();
                  _elem44 = new Contact();
                  _elem44.Read(iprot);
                  Users.Add(_elem44);
                }
                iprot.ReadListEnd();
              }
            } else { 
              TProtocolUtil.Skip(iprot, field.Type);
            }
            break;
          case 2:
            if (field.Type == TType.List) {
              {
                Buddies = new List<Contact>();
                TList _list45 = iprot.ReadListBegin();
                for( int _i46 = 0; _i46 < _list45.Count; ++_i46)
                {
                  Contact _elem47 = new Contact();
                  _elem47 = new Contact();
                  _elem47.Read(iprot);
                  Buddies.Add(_elem47);
                }
                iprot.ReadListEnd();
              }
            } else { 
              TProtocolUtil.Skip(iprot, field.Type);
            }
            break;
          default: 
            TProtocolUtil.Skip(iprot, field.Type);
            break;
        }
        iprot.ReadFieldEnd();
      }
      iprot.ReadStructEnd();
    }

    public void Write(TProtocol oprot) {
      TStruct struc = new TStruct("ProximityMatchCandidateResult");
      oprot.WriteStructBegin(struc);
      TField field = new TField();
      if (Users != null && __isset.users) {
        field.Name = "users";
        field.Type = TType.List;
        field.ID = 1;
        oprot.WriteFieldBegin(field);
        {
          oprot.WriteListBegin(new TList(TType.Struct, Users.Count));
          foreach (Contact _iter48 in Users)
          {
            _iter48.Write(oprot);
          }
          oprot.WriteListEnd();
        }
        oprot.WriteFieldEnd();
      }
      if (Buddies != null && __isset.buddies) {
        field.Name = "buddies";
        field.Type = TType.List;
        field.ID = 2;
        oprot.WriteFieldBegin(field);
        {
          oprot.WriteListBegin(new TList(TType.Struct, Buddies.Count));
          foreach (Contact _iter49 in Buddies)
          {
            _iter49.Write(oprot);
          }
          oprot.WriteListEnd();
        }
        oprot.WriteFieldEnd();
      }
      oprot.WriteFieldStop();
      oprot.WriteStructEnd();
    }

    public override string ToString() {
      StringBuilder sb = new StringBuilder("ProximityMatchCandidateResult(");
      sb.Append("Users: ");
      sb.Append(Users);
      sb.Append(",Buddies: ");
      sb.Append(Buddies);
      sb.Append(")");
      return sb.ToString();
    }

  }

}
