/**
 * Autogenerated by Thrift Compiler (0.9.1)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
using System;
using System.Collections;
using System.Collections.Generic;
using System.Text;
using System.IO;
using Thrift;
using Thrift.Collections;
using System.Runtime.Serialization;
using Thrift.Protocol;
using Thrift.Transport;

namespace LineSharp.Datatypes
{

  #if !SILVERLIGHT
  [Serializable]
  #endif
  public partial class SnsIdUserStatus : TBase
  {
    private bool _userExisting;
    private bool _phoneNumberRegistered;
    private bool _sameDevice;

    public bool UserExisting
    {
      get
      {
        return _userExisting;
      }
      set
      {
        __isset.userExisting = true;
        this._userExisting = value;
      }
    }

    public bool PhoneNumberRegistered
    {
      get
      {
        return _phoneNumberRegistered;
      }
      set
      {
        __isset.phoneNumberRegistered = true;
        this._phoneNumberRegistered = value;
      }
    }

    public bool SameDevice
    {
      get
      {
        return _sameDevice;
      }
      set
      {
        __isset.sameDevice = true;
        this._sameDevice = value;
      }
    }


    public Isset __isset;
    #if !SILVERLIGHT
    [Serializable]
    #endif
    public struct Isset {
      public bool userExisting;
      public bool phoneNumberRegistered;
      public bool sameDevice;
    }

    public SnsIdUserStatus() {
    }

    public void Read (TProtocol iprot)
    {
      TField field;
      iprot.ReadStructBegin();
      while (true)
      {
        field = iprot.ReadFieldBegin();
        if (field.Type == TType.Stop) { 
          break;
        }
        switch (field.ID)
        {
          case 1:
            if (field.Type == TType.Bool) {
              UserExisting = iprot.ReadBool();
            } else { 
              TProtocolUtil.Skip(iprot, field.Type);
            }
            break;
          case 2:
            if (field.Type == TType.Bool) {
              PhoneNumberRegistered = iprot.ReadBool();
            } else { 
              TProtocolUtil.Skip(iprot, field.Type);
            }
            break;
          case 3:
            if (field.Type == TType.Bool) {
              SameDevice = iprot.ReadBool();
            } else { 
              TProtocolUtil.Skip(iprot, field.Type);
            }
            break;
          default: 
            TProtocolUtil.Skip(iprot, field.Type);
            break;
        }
        iprot.ReadFieldEnd();
      }
      iprot.ReadStructEnd();
    }

    public void Write(TProtocol oprot) {
      TStruct struc = new TStruct("SnsIdUserStatus");
      oprot.WriteStructBegin(struc);
      TField field = new TField();
      if (__isset.userExisting) {
        field.Name = "userExisting";
        field.Type = TType.Bool;
        field.ID = 1;
        oprot.WriteFieldBegin(field);
        oprot.WriteBool(UserExisting);
        oprot.WriteFieldEnd();
      }
      if (__isset.phoneNumberRegistered) {
        field.Name = "phoneNumberRegistered";
        field.Type = TType.Bool;
        field.ID = 2;
        oprot.WriteFieldBegin(field);
        oprot.WriteBool(PhoneNumberRegistered);
        oprot.WriteFieldEnd();
      }
      if (__isset.sameDevice) {
        field.Name = "sameDevice";
        field.Type = TType.Bool;
        field.ID = 3;
        oprot.WriteFieldBegin(field);
        oprot.WriteBool(SameDevice);
        oprot.WriteFieldEnd();
      }
      oprot.WriteFieldStop();
      oprot.WriteStructEnd();
    }

    public override string ToString() {
      StringBuilder sb = new StringBuilder("SnsIdUserStatus(");
      sb.Append("UserExisting: ");
      sb.Append(UserExisting);
      sb.Append(",PhoneNumberRegistered: ");
      sb.Append(PhoneNumberRegistered);
      sb.Append(",SameDevice: ");
      sb.Append(SameDevice);
      sb.Append(")");
      return sb.ToString();
    }

  }

}
