/**
 * Autogenerated by Thrift Compiler (0.9.1)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */

namespace LINE.Datatypes
{
  public enum EmailConfirmationType
  {
    SERVER_SIDE_EMAIL = 0,
    CLIENT_SIDE_EMAIL = 1,
  }
}
