/**
 * Autogenerated by Thrift Compiler (0.9.1)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */

namespace LINE.Datatypes
{
  public enum EmailConfirmationStatus
  {
    NOT_SPECIFIED = 0,
    NOT_YET = 1,
    DONE = 3,
  }
}
