/**
 * Autogenerated by Thrift Compiler (0.9.1)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */

namespace LINE.Datatypes
{
  public enum IdentityProvider
  {
    UNKNOWN = 0,
    LINE = 1,
    NAVER_KR = 2,
  }
}
