/**
 * Autogenerated by Thrift Compiler (0.9.1)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */

namespace LINE.Datatypes
{
  public enum PayloadType
  {
    PAYLOAD_BUY = 101,
    PAYLOAD_CS = 111,
    PAYLOAD_BONUS = 121,
    PAYLOAD_EVENT = 131,
  }
}
