/**
 * Autogenerated by Thrift Compiler (0.9.1)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */

namespace LINE.Datatypes
{
  public enum PaymentType
  {
    PAYMENT_APPLE = 1,
    PAYMENT_GOOGLE = 2,
  }
}
