/**
 * Autogenerated by Thrift Compiler (0.9.1)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */

namespace LINE.Datatypes
{
  public enum PaymentPgType
  {
    PAYMENT_PG_NONE = 0,
    PAYMENT_PG_AU = 1,
    PAYMENT_PG_AL = 2,
  }
}
