/**
 * Autogenerated by Thrift Compiler (0.9.1)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */

namespace LINE.Datatypes
{
  public enum ProductBannerLinkType
  {
    BANNER_LINK_NONE = 0,
    BANNER_LINK_ITEM = 1,
    BANNER_LINK_URL = 2,
    BANNER_LINK_CATEGORY = 3,
  }
}
