/**
 * Autogenerated by Thrift Compiler (0.9.1)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */

namespace LINE.Datatypes
{
  public enum ProductEventType
  {
    NO_EVENT = 0,
    CARRIER_ANY = 65537,
    BUDDY_ANY = 131073,
    INSTALL_IOS = 196609,
    INSTALL_ANDROID = 196610,
    MISSION_ANY = 262145,
    MUSTBUY_ANY = 327681,
  }
}
