/**
 * Autogenerated by Thrift Compiler (0.9.1)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
using System;
using System.Collections;
using System.Collections.Generic;
using System.Text;
using System.IO;
using Thrift;
using Thrift.Collections;
using System.Runtime.Serialization;
using Thrift.Protocol;
using Thrift.Transport;

namespace LINE.Datatypes
{

  #if !SILVERLIGHT
  [Serializable]
  #endif
  public partial class RegisterWithSnsIdResult : TBase
  {
    private string _authToken;
    private bool _userCreated;

    public string AuthToken
    {
      get
      {
        return _authToken;
      }
      set
      {
        __isset.authToken = true;
        this._authToken = value;
      }
    }

    public bool UserCreated
    {
      get
      {
        return _userCreated;
      }
      set
      {
        __isset.userCreated = true;
        this._userCreated = value;
      }
    }


    public Isset __isset;
    #if !SILVERLIGHT
    [Serializable]
    #endif
    public struct Isset {
      public bool authToken;
      public bool userCreated;
    }

    public RegisterWithSnsIdResult() {
    }

    public void Read (TProtocol iprot)
    {
      TField field;
      iprot.ReadStructBegin();
      while (true)
      {
        field = iprot.ReadFieldBegin();
        if (field.Type == TType.Stop) { 
          break;
        }
        switch (field.ID)
        {
          case 1:
            if (field.Type == TType.String) {
              AuthToken = iprot.ReadString();
            } else { 
              TProtocolUtil.Skip(iprot, field.Type);
            }
            break;
          case 2:
            if (field.Type == TType.Bool) {
              UserCreated = iprot.ReadBool();
            } else { 
              TProtocolUtil.Skip(iprot, field.Type);
            }
            break;
          default: 
            TProtocolUtil.Skip(iprot, field.Type);
            break;
        }
        iprot.ReadFieldEnd();
      }
      iprot.ReadStructEnd();
    }

    public void Write(TProtocol oprot) {
      TStruct struc = new TStruct("RegisterWithSnsIdResult");
      oprot.WriteStructBegin(struc);
      TField field = new TField();
      if (AuthToken != null && __isset.authToken) {
        field.Name = "authToken";
        field.Type = TType.String;
        field.ID = 1;
        oprot.WriteFieldBegin(field);
        oprot.WriteString(AuthToken);
        oprot.WriteFieldEnd();
      }
      if (__isset.userCreated) {
        field.Name = "userCreated";
        field.Type = TType.Bool;
        field.ID = 2;
        oprot.WriteFieldBegin(field);
        oprot.WriteBool(UserCreated);
        oprot.WriteFieldEnd();
      }
      oprot.WriteFieldStop();
      oprot.WriteStructEnd();
    }

    public override string ToString() {
      StringBuilder sb = new StringBuilder("RegisterWithSnsIdResult(");
      sb.Append("AuthToken: ");
      sb.Append(AuthToken);
      sb.Append(",UserCreated: ");
      sb.Append(UserCreated);
      sb.Append(")");
      return sb.ToString();
    }

  }

}
