/**
 * Autogenerated by Thrift Compiler (0.9.1)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */

namespace LINE.Datatypes
{
  public enum SpammerReason
  {
    OTHER = 0,
    ADVERTISING = 1,
    GENDER_HARASSMENT = 2,
    HARASSMENT = 3,
  }
}
