/**
 * Autogenerated by Thrift Compiler (0.9.1)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */

namespace LINE.Datatypes
{
  public enum SyncCategory
  {
    PROFILE = 0,
    SETTINGS = 1,
    OPS = 2,
    CONTACT = 3,
    RECOMMEND = 4,
    BLOCK = 5,
    GROUP = 6,
    ROOM = 7,
    NOTIFICATION = 8,
  }
}
