/**
 * Autogenerated by Thrift Compiler (0.9.1)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */

namespace LineSharp.Datatypes
{
  public enum ModificationType
  {
    ADD = 0,
    REMOVE = 1,
    MODIFY = 2,
  }
}
